name: build-test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "copy tool file with test values"
        run: cat __tests__/tool-versions > .tool-versions
      - uses: ./
        id: versions
      - name: "check exported env vars"
        run: ./.github/workflows/scripts/test/test-envs.sh
      - name: "check action output JSON"
        run: ./.github/workflows/scripts/test/test-json.sh '${{ steps.versions.outputs.tools }}'
  test-wd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        id: custom_versions_file
        with:
          working_directory: ./__tests__
      - name: "check exported env vars"
        run: ./.github/workflows/scripts/test/test-envs.sh
      - name: "check action output JSON"
        run: ./.github/workflows/scripts/test/test-json.sh '${{ steps.custom_versions_file.outputs.tools }}'

